server:
  port: 8080

feign.client.config.logger.level: FULL

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:camunda;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

#camunda
camunda:
  bpm:
    authorization:
      enabled: false
    admin-user:
      id: admin
      password: admin
    generic-properties:
      properties:
        historyTimeToLive: P10D

#Parametros do KC adicionados somente para a aplicação subir, porém o KC não é utilizado no perfil local
keycloak:
  url: http://localhost:9000/auth
  client:
    realm: camunda
    id: camunda
    secret: G1RZe6zORs6Gavi3q6DxR0UFAA6Je4qi


